version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_INITDB_DATABASE=weather-forecast
    volumes:
      - ./mongo/data:/data/db
    ports:
      - '27017:27017'
