version: '3'

services:
  app:
    env_file:
      - .env
    container_name: weather-forecast-service
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - ./:/var/app
      - /var/app/node_modules
    ports:
      - '9000:9000'
    depends_on:
      - database
    links:
      - database

  database:
    container_name: weather-forecast-db
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db
    ports:
      - '27017:27017'
